[package]
name = "closures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.uuid]
uuid = "1.4.1"
features = [
    "v4",
    "v7",
    "js",
]
